
name: Deploy Frontend to Azure - cloud-task-app-frontend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: npm install and build
        run: |
          cd frontend
          npm install
          npm run build

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'cloud-task-app-frontend' 
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_83C0F0237CDE43869AFA61A2355B3060 }}
          package: frontend/dist